# Generated by Django 5.1.6 on 2025-04-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoapp', '0003_croprecommendation'),
    ]

    operations = [
        migrations.CreateModel(
            name='FertilizerRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('moisture', models.FloatField()),
                ('soil', models.CharField(max_length=20)),
                ('crop', models.CharField(max_length=20)),
                ('nitrogen', models.IntegerField()),
                ('phosphorous', models.IntegerField()),
                ('potassium', models.IntegerField()),
                ('predicted_fertilizer', models.CharField(max_length=50)),
            ],
        ),
    ]
